[package]
name = "ai-fn"
version = "0.1.0"
edition = "2021"

[dependencies]
async-openai = "0.10.1"
tokio = { version = "1.27.0", features = ["full"] }
reqwest = { version = "0.11.16", features = ["blocking"] }
rand = "0.8.5"
select = "0.6.0"
ai-fn-macro = { path = "../ai-fn-macro" }